-- Create a simple 'registrations' table in Supabase.
-- Dashboard: https://supabase.com/dashboard/project/xpdfiptmcghvgbbygrfi/sql/new

CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT NOT NULL,
  notes TEXT,
  timestamp TEXT
);

-- Enable RLS (Disable for initial testing if you want public inserts)
ALTER TABLE registrations DISABLE ROW LEVEL SECURITY;
